sdf_map/box_min_x: -25.0
sdf_map/box_min_y: -25.0
sdf_map/box_min_z: 0.7

sdf_map/box_max_x: 25.0
sdf_map/box_max_y: 25.0
sdf_map/box_max_z: 1.7

sdf_map/map_size_x: 55.0
sdf_map/map_size_y: 55.0
sdf_map/map_size_z: 3.0

sdf_map/resolution: 0.15
max_allowed_time: 1800.0 # 30 min
